import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createSharedLibrary,firebaseTransport,createRevision,ConflictError} from '../src/shared-library.js';
const enabled=process.env.BIOGLOW_EMULATOR_TEST==='1';
const origin=process.env.BIOGLOW_DATABASE_ORIGIN||'http://127.0.0.1:9008',ns=process.env.BIOGLOW_DEMO_PROJECT||'demo-bioglow';
const authOrigin=process.env.BIOGLOW_AUTH_ORIGIN||'http://127.0.0.1:9098';
const fixture=()=>({version:1,workspace:{blocks:{languageVersion:0,blocks:[{type:'sim_start',id:'start',x:40,y:60}]}},start:{x:330,y:410,h:47}});
const identifier=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('');
async function auth(){const r=await fetch(authOrigin+'/identitytoolkit.googleapis.com/v1/accounts:signUp?key=demo-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({returnSecureToken:true})});const v=await r.json();assert.ok(v.idToken);return {uid:v.localId,token:async()=>v.idToken};}
async function raw(path,body,who,method='PATCH',query={}){const url=new URL(path+'.json',origin);url.searchParams.set('ns',ns);if(who)url.searchParams.set('auth',await who.token());for(const[k,v]of Object.entries(query))url.searchParams.set(k,String(v));return fetch(url,{method,headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});}
test('Realtime Database emulator: shared editing and security',{skip:!enabled},async t=>{
 const rules=await readFile(new URL('../firebase/database.rules.json',import.meta.url),'utf8');
 const setup=await fetch(`${origin}/.settings/rules.json?ns=${ns}`,{method:'PUT',headers:{Authorization:'Bearer owner'},body:rules});assert.equal(setup.status,200,await setup.text());
 const alice=await auth(),bob=await auth();
 const make=who=>createSharedLibrary({session:async()=>who,request:firebaseTransport({databaseURL:origin,namespace:ns,session:async()=>who})});
 const a=make(alice),b=make(bob);let first,second;
 await t.test('A creates; B loads exact workspace and pose',async()=>{first=await a.save({name:'Test mission',payload:fixture()});assert.deepEqual((await b.load(first.id)).payload,fixture());});
 await t.test('B edits A program without owner lockout',async()=>{const payload=fixture();payload.start.h=90;second=await b.save({programId:first.id,base:first.meta,name:first.meta.name,nickname:'Blue team',payload});assert.equal(second.meta.seq,2);assert.equal((await a.load(first.id)).payload.start.h,90);});
 await t.test('stale saves do not change current revision or history',async()=>{await assert.rejects(a.save({programId:first.id,base:first.meta,name:first.meta.name,payload:fixture()}),ConflictError);assert.equal((await a.header(first.id)).revision,second.meta.revision);assert.equal((await a.history(first.id)).items.length,2);});
 await t.test('restore appends revision and preserves old content',async()=>{const old=await a.load(first.id,first.meta.revision);const restored=await a.save({programId:first.id,base:second.meta,name:first.meta.name,payload:old.payload,restoredFrom:first.meta.revision});assert.equal(restored.meta.seq,3);assert.deepEqual((await b.load(first.id)).payload,fixture());assert.equal((await b.load(first.id,second.meta.revision)).payload.start.h,90);second=restored;});
 await t.test('Save a copy creates new ID and version 1',async()=>{const copy=await b.save({name:'Copy',payload:fixture()});assert.notEqual(copy.id,first.id);assert.equal(copy.meta.seq,1);});
 await t.test('concurrent writers have exactly one winner',async()=>{const out=await Promise.allSettled([a,b].map(api=>api.save({programId:first.id,base:second.meta,name:first.meta.name,payload:fixture()})));assert.equal(out.filter(r=>r.status==='fulfilled').length,1);assert.ok(out.find(r=>r.status==='rejected').reason instanceof ConflictError);});
 const denied=async(path,body,method='PATCH',who=alice)=>{const r=await raw(path,body,who,method);assert.equal(r.status,401,await r.text());};
 await t.test('unauthenticated access denied',async()=>{await denied('/bioglowV1',createRevision({programId:identifier(),uid:alice.uid,name:'No auth',payload:fixture()}),'PATCH',null);await denied('/bioglowV1/catalog',undefined,'GET',null);});
 await t.test('root and unbounded collections cannot be downloaded',async()=>{for(const p of ['/bioglowV1','/bioglowV1/catalog',`/bioglowV1/history/${first.id}`,`/bioglowV1/payloads/${first.id}`])await denied(p,undefined,'GET');const r=await raw('/bioglowV1/catalog',undefined,alice,'GET',{orderBy:'"$key"',limitToFirst:51});assert.equal(r.status,401);});
 await t.test('old history/payloads cannot be modified or deleted',async()=>{for(const p of [`/bioglowV1/history/${first.id}/${first.meta.revision}`,`/bioglowV1/payloads/${first.id}/${first.meta.revision}`,`/bioglowV1/history/${first.id}`,`/bioglowV1/payloads/${first.id}`,`/bioglowV1/catalog/${first.id}`])await denied(p,null,'DELETE');await denied(`/bioglowV1/payloads/${first.id}/${first.meta.revision}`,{start:{x:2,y:3,h:4}});await denied(`/bioglowV1/history/${first.id}/${first.meta.revision}`,{name:'tampered'});});
 const bad=async mutate=>{const pid=identifier(),patch=createRevision({programId:pid,uid:alice.uid,name:'Security test',payload:fixture()});mutate(patch,pid);await denied('/bioglowV1',patch);};
 await t.test('reject unexpected envelope and pose fields',async()=>{await bad((p,id)=>p['catalog/'+id].admin=true);await bad(p=>Object.values(p).find(v=>v.workspace).start.z=1);await bad(p=>Object.values(p).find(v=>v.workspace).secret='no');});
 await t.test('reject bad names, spoofed UID, invalid sequence/time',async()=>{for(const change of [v=>v.name='../bad',v=>v.uid=bob.uid,v=>v.seq=1.5,v=>v.nickname='<script>',v=>v.updatedAt=1])await bad((p,id)=>{change(p['catalog/'+id]);change(Object.values(p).find(v=>Object.hasOwn(v,'previous')));});});
 await t.test('reject oversized payload and invalid pose',async()=>{await bad(p=>Object.values(p).find(v=>v.workspace).workspace='x'.repeat(131073));for(const pose of [{x:-1,y:0,h:0},{x:0,y:1144,h:0},{x:0,y:0,h:'90'},{x:0,y:0,h:1e7}])await bad(p=>Object.values(p).find(v=>v.workspace).start=pose);});
 await t.test('reject incomplete atomic saves and forged previous link',async()=>{for(const prefix of ['catalog/','history/','payloads/'])await bad(p=>delete p[Object.keys(p).find(k=>k.startsWith(prefix))]);await bad(p=>Object.values(p).find(v=>Object.hasOwn(v,'previous')).previous=identifier());});
 await t.test('rules cannot parse workspace JSON; client rejects corrupt content',async()=>{const pid=identifier(),p=createRevision({programId:pid,uid:alice.uid,name:'Corrupt fixture',payload:fixture()});Object.values(p).find(v=>v.workspace).workspace='{invalid JSON';const r=await raw('/bioglowV1',p,alice);assert.equal(r.status,200,await r.text());await assert.rejects(a.load(pid));});
 await t.test('list returns bounded metadata without payloads',async()=>{const page=await a.list();assert.ok(page.items.length<=20);assert.ok(page.items.every(x=>!Object.hasOwn(x,'workspace')));});
});
